name: Auto Assign Labels and Assignees
on:
  pull_request_target:
    types: ["opened", "reopened", "ready_for_review"]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
    if: ${{ github.event.pull_request.draft == false }}
  assign_based_on_labels:
    runs-on: ubuntu-latest
    needs: triage
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: WaitForLabel
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '60'
      - name: Set Assignees
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./\.github/workflows/assignee.js')
            script({github, context})
