name: Auto Assign Label and Reviewer
on:
  pull_request_target:
    types: ["labeled"]

jobs: 
  add_assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set Assignees
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const assignees = [];
            const labelsToAssignees = {
              'product: CLion': ['sgowroji'],
              'product: IntelliJ': ['tilakrayal'],
              'product: GoLand': ['chunduriv'],
              'product: Android Studio': ['sgowroji']
              // Add more label-assignee mappings here
            };
            for (const label of labels) {
              if (label in labelsToAssignees) {
                assignees.push(...labelsToAssignees[label]);
              }
            }
            if (assignees.length > 0) {
              const issue_number = context.payload.pull_request.number;
              await github.issues.addAssignees({
                issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees
              });
            }
